version: '3.3'
volumes:
  mysql_data:
    driver: local
services:

  #MYSQL
  mysql:
    image: mysql:8.0.19
    command: --lower_case_table_names=1
    container_name: mysql_Clientes
    ports:
      - "3346:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Clientes
      MYSQL_USER: Clientes
      MYSQL_PASSWORD: root

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: Clientes
      DB_USER: Clientes
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - mysql

  rabbitmq:
    image: rabbitmq:3-management
    command: rabbitmq-server
    ports:
      - "15670:15672"
      - "5674:5672"
      - "5673:5671"
    environment:
      - RABBITMQ_DEFAULT_VHOST=MarcosVinicius-dev
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5

